index, event, this and error confusion fixed
index (1): mixed up a player and an index variable

index (2): added RankingNumGamesListener to the index

event: RankingModel fired an 'insert' event. Should have been 'result'

this: RankingNumGamesListener: forgot a "this" during array iteration

error: RankingDataListenerIndex missing-name-error improved by directly
printing the missing name